# Activit 7

## Exercise 07.1

In [1]:
import numpy as np
x = np.random.rand(10000)
y = np.random.rand(10000)
%time z = np.add(x, y)
print(z)

CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 58.7 µs
[ 0.46733546  1.85213476  0.46397342 ...,  1.19612951  0.41730415
  0.60468279]


In [2]:
def compute_add(x, y):
    z = []
    for i in range(len(x)):
        z.append (x[i] + y[i])
    return np.array(z)
%time z = compute_add(x, y)
print(z)

CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 4.15 ms
[ 0.46733546  1.85213476  0.46397342 ...,  1.19612951  0.41730415
  0.60468279]


## Exercise 07.2

In [3]:
z = np.array([58.0, 35.0, 24.0, 42, 7.8])
s = z / 60
s.sort()
print(s)

[ 0.13        0.4         0.58333333  0.7         0.96666667]


In [4]:
print('The min is {}, max is {} and mean is {}.'.format(s.min(), s.max(), s.mean()))

The min is 0.13, max is 0.9666666666666667 and mean is 0.5559999999999999.


In [5]:
a = s[1:][:-1]
print('The min is {}, max is {} and mean is {}.'.format(a.min(), a.max(), a.mean()))

The min is 0.4, max is 0.7 and mean is 0.5611111111111111.


## Exercise 07.3

In [6]:
A = np.array([[4.0, 7.0, -2.43, 67.1],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])
print (A)

[[   4.      7.     -2.43   67.1 ]
 [  -4.     64.     54.7    -3.33]
 [   2.43   23.2     3.64    4.11]
 [   1.2     2.5  -113.2   323.22]]


In [7]:
print (A[0])

[  4.     7.    -2.43  67.1 ]


In [8]:
print (A[:,:2])

[[  4.     7.  ]
 [ -4.    64.  ]
 [  2.43  23.2 ]
 [  1.2    2.5 ]]


In [9]:
print (A[2:,2:])

[[   3.64    4.11]
 [-113.2   323.22]]


In [10]:
print (A.transpose())

[[   4.     -4.      2.43    1.2 ]
 [   7.     64.     23.2     2.5 ]
 [  -2.43   54.7     3.64 -113.2 ]
 [  67.1    -3.33    4.11  323.22]]


In [11]:
B = A[3]
print (np.sum(B))#
print ('Expected to be {}.'.format(1.2 + 2.5 - 113.2 + 323.22))

213.72
Expected to be 213.72000000000003.
