# Exercise 07 Solutions

## Exersice 07.1
Summing arrays using two methods and comparing times

In [1]:
import numpy as np

x = np.random.rand(8000000)
y = np.random.rand(8000000)



%time z1 = x + y


%time z2 = [x[n] + y[n] for n in range(len(x)) ]


CPU times: user 16 ms, sys: 20 ms, total: 36 ms
Wall time: 38.3 ms
CPU times: user 4.21 s, sys: 116 ms, total: 4.33 s
Wall time: 4.33 s


It is very clear that the system employed by numpy to summate the arrays x and y is far more efficient than using a for loop to iterate over each value and find its sum

## Exercise 07.2
Script to take and analyise raw scrores for an examination in various ways

In [4]:
import numpy as np

scores = np.array([58.0, 35.0, 24.0, 42, 7.8])

def sorted_scores(raw_scores):
    raw_scores = raw_scores / 60 * 100
    return np.sort(raw_scores)

def score_analysis(raw_scores, exclude=False):
    raw_scores = raw_scores / 60 * 100

    if exclude == True:
        np.sort(raw_scores)
        raw_scores = raw_scores[1:-1]
    
    return raw_scores.min(), raw_scores.max(), raw_scores.mean()

print(sorted_scores(scores))
print(score_analysis(scores,True))

[ 13.          40.          58.33333333  70.          96.66666667]
(40.0, 70.0, 56.111111111111114)


## Exercise 07.3
Array slicing

In [3]:
A = np.array([[4.0, 7.0, -2.43, 67.1,],
             [-4.0, 64.0, 54.7, -3.33],
             [2.43, 23.2, 3.64, 4.11],
             [1.2, 2.5, -113.2, 323.22]])

A_col3 = A[:,2]
A_row1_2 = A[0:2,:]
A_block = A[-2:,-2:]
trans_A = A.transpose()
A_sum_last = np.sum(A[:,-1])


print(A_col3,"\n")
print(A_row1_2,"\n")
print(A_block,"\n")
print(trans_A,"\n")
print(A_sum_last)

[  -2.43   54.7     3.64 -113.2 ] 

[[  4.     7.    -2.43  67.1 ]
 [ -4.    64.    54.7   -3.33]] 

[[   3.64    4.11]
 [-113.2   323.22]] 

[[   4.     -4.      2.43    1.2 ]
 [   7.     64.     23.2     2.5 ]
 [  -2.43   54.7     3.64 -113.2 ]
 [  67.1    -3.33    4.11  323.22]] 

391.1


## Exercise 07.4 
SciPy bisect V own bisect

In [38]:
from scipy import optimize

def func_x(x):
    return x**4 + 3*x**3 - 8*x**2 - 6*x + 1 + - np.exp(x)

def bisect_func(f, x0, x1, tol=1e-6, max_it=50):

    
    for num_it in range(0, max_it):
        x_mid = (x1 + x0) / 2
        func_x_mid = f(x_mid)
        func_x0 = f(x0)
        
        if abs(func_x_mid) <= tol:
            break
        
        elif func_x_mid * func_x0 < 0:
            x1 = x_mid
        else:
            x0 = x_mid

    return x_mid

%time print(optimize.bisect(func_x,-5,-4,xtol=1e-8,maxiter=50))
%time print(bisect_func(func_x,-5,-4,1e-8,50))



-4.476638473570347
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 295 µs
-4.476638468448073
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 248 µs
